### ISSUE TITLE
Changing repo topics

### ISSUE THREAD

**Issue by moeenio** [VFDan/VFDan.github.io#1]
The `vfdan` topic is only used by you, so it will not improve the visibility of the repo. You could add `jekyll`, since it powers GitHub Pages.

**Comment by VFDan** [comment]
What do you mean by "repo topic"?
(And sorry for the excruciatingly late reply)

**Comment by moeenio** [comment]
By "repo topics" I mean the tag thingies below the repo description

**Comment by VFDan** [comment]
Changed
